"""
write_readme.py

Reads the freshly-generated SVGs from /tmp/repo/assets and emits README.md
with clickable cards INLINED as live DOM <svg>...</svg> blocks (so
<a xlink:href> hotspots actually fire) and non-clickable cards kept as
<img src="assets/...svg"> references.

Why: GitHub renders <img src="*.svg"> as a flat image; clicks on hotspots
inside it go to the .svg file itself. Inlining the SVG in the README turns
each hotspot into a real <a> tag that the browser follows.
"""

import json, html
from pathlib import Path

ROOT = Path(__file__).resolve().parent
REPO = Path("/tmp/repo")
ASSETS = REPO / "assets"

with open(ROOT / "terminal_data.json", encoding="utf-8") as f:
    DATA = json.load(f)

# Cards that contain clickable hotspots -> inline these as DOM SVG
INLINE_CARDS = set(DATA.get("inline_cards", ["hero", "projects", "certifications", "connect"]))


def svg_inline(slug):
    """Read the .svg and return the full <svg ...>...</svg> block, ready to embed."""
    p = ASSETS / f"terminal-{slug}.svg"
    if not p.exists():
        raise FileNotFoundError(f"missing asset: {p} -- run generate_live.py first")
    return p.read_text(encoding="utf-8").strip()


def img_card(slug, alt):
    return f'<img src="assets/terminal-{slug}.svg" alt="{html.escape(alt)}"/>'


def img_bar(slug, alt):
    return f'<img src="assets/bar-{slug}.svg" alt="{html.escape(alt)}"/>'


def centered_inline(svg_text, max_width_px=None):
    """Wrap an inline-SVG block in a centered paragraph. Optionally constrain width."""
    style = ""
    if max_width_px:
        style = f' style="max-width:{max_width_px}px;width:100%;height:auto"'
    inner = svg_text
    return f'<p align="center"{style}>{inner}</p>'


def centered_img(img_tag):
    return f'<p align="center">{img_tag}</p>'


# Build README
parts = []

# Hero (inline)
parts.append(centered_inline(svg_inline("hero"), max_width_px=900))
parts.append(
    '<p align="center">'
    '<img src="https://komarev.com/ghpvc/?username=shanujans&style=flat-square&color=5299d2&label=PROFILE+VIEWS" alt="profile views"/>'
    '</p>'
)
parts.append('<hr/>')

# About + fastfetch (fastfetch is a PNG, meta/about are visual-only)
parts.append(img_bar("about", "$ whoami"))
parts.append(
    '<p align="center">'
    '<img src="assets/fastfetch.png" alt="shanujansh@github fastfetch" width="880"/>'
    '</p>'
)
parts.append(centered_img(img_card("about", "About & Skills")))

# System Meta (live uptime)
parts.append(img_bar("meta", "$ uname -a"))
parts.append(centered_img(img_card("meta", "System Meta")))

# Languages
parts.append(img_bar("languages", "$ which -a --languages"))
parts.append(centered_img(img_card("languages", "Languages")))

# Focus Areas
parts.append(img_bar("focus", "$ focus --areas"))
parts.append(centered_img(img_card("focus", "Focus Areas")))

# Tools
parts.append(img_bar("tools", "$ which -a --tools"))
parts.append(centered_img(img_card("tools", "Tools I Work With")))

parts.append('<hr/>')

# Projects (inline - project titles are clickable)
parts.append(img_bar("projects", "$ ls ./projects --featured"))
parts.append(centered_inline(svg_inline("projects"), max_width_px=900))

parts.append('<hr/>')

# Certifications (inline - cert rows are clickable)
parts.append(img_bar("certifications", "$ cat certifications.log"))
parts.append(centered_inline(svg_inline("certifications"), max_width_px=900))
parts.append(
    '<sub>Replace the placeholder <code>verify_url</code> values for each cert in '
    '<code>scripts/terminal_data.json</code> with your real Issuer verification URLs '
    '(Credly / IBM SkillsBuild / Cisco NetAcad etc.) to make the rows link to your '
    'credential pages.</sub>'
)

parts.append('<hr/>')

# Stats (imagemap - stats card is non-clickable)
parts.append(img_bar("stats", "$ gh stats --user shanujans"))
parts.append(centered_img(img_card("stats", "GitHub Stats")))
parts.append(
    '<sub>This card is regenerated by <code>.github/workflows/refresh-terminal.yml</code> '
    'using live GitHub API data + the <code>last_known_loc</code> baseline in '
    '<code>scripts/terminal_data.json</code>. Each regeneration stamps '
    '<code>// last synced YYYY-MM-DD HH:MM UTC</code> at the bottom of the card.</sub>'
)

# External widgets - kept for the richer view beneath the stats
parts.append(
    '<p align="center">'
    '<a href="https://github.com/shanujans"><img src="https://github-readme-stats.vercel.app/api?username=shanujans&show_icons=true&hide_border=true&bg_color=0d1117&title_color=ca7938&icon_color=5299d2&text_color=a0b3bc"></a>'
    '<a href="https://github.com/shanujans"><img src="https://github-readme-stats.vercel.app/api/top-langs/?username=shanujans&layout=compact&hide_border=true&bg_color=0d1117&title_color=ca7938&text_color=a0b3bc"></a>'
    '</p>'
)
parts.append(
    '<p align="center">'
    '<a href="https://github.com/shanujans"><img src="https://streak-stats.demolab.com?user=shanujans&hide_border=true&background=0d1117&border=0d1117&ring=ca7938&fire=5299d2&currStreakNum=ffffff&currStreakLabel=ca7938&sideNums=a0b3bc&sideLabels=a0b3bc&dates=5c6773"></a>'
    '</p>'
)
parts.append(
    '<sub>⚠️ The three widgets above are rendered live by external services — their '
    'font is fixed there; only colors are matched to the terminal palette.</sub>'
)

parts.append('<hr/>')

# Activity
parts.append(img_bar("activity", "$ gh activity --graph"))
parts.append(
    '<p align="center">'
    '<a href="https://github.com/shanujans"><img src="https://github-readme-activity-graph.vercel.app/graph?username=shanujans&hide_border=true&bg_color=0d1117&color=a0b3bc&line=ca7938&point=5299d2&area=true&area_color=5299d2"></a>'
    '</p>'
)

parts.append('<hr/>')

# Snake
parts.append(img_bar("snake", "$ ./snake --eat contributions"))
parts.append(
    '<p align="center">'
    '<img src="https://raw.githubusercontent.com/shanujans/shanujans/output/github-contribution-grid-snake.svg" alt="snake"/>'
    '</p>'
)
parts.append(
    '<sub>To recolor the snake itself, add these query params to your `Platane/snk` workflow output line:</sub>'
)
parts.append(
    "```yaml\noutputs: |\n  dist/github-contribution-grid-snake.svg?color_snake=%23ca7938"
    "&color_dots=%230d1117,%231b2b3a,%232f5a86,%235299d2,%23ca7938\n```"
)

parts.append('<hr/>')

# Connect (inline - email/portfolio/github/linkedin are clickable)
parts.append(img_bar("connect", "$ cat contact.md"))
parts.append(centered_inline(svg_inline("connect"), max_width_px=900))

parts.append(
    '<p align="center">'
    '📬 <a href="mailto:shanujansh@gmail.com">Email</a> · '
    '<a href="https://shanujan.is-a.dev">Portfolio</a> · '
    '<a href="https://github.com/shanujans">GitHub</a> · '
    '<a href="https://www.linkedin.com/in/shanujansuresh/">LinkedIn</a>'
    '</p>'
)


readme_md = "\n\n".join(parts) + "\n"

readme_path = REPO / "README.md"
readme_path.write_text(readme_md, encoding="utf-8")

# Quick stats
size_kb = readme_path.stat().st_size / 1024
inline_chars = readme_md.count("<svg ")
img_count = readme_md.count('<img src="assets/')
hit = readme_md.count('xlink:href')

print(f"Wrote {readme_path}  ({size_kb:.1f} KB)")
print(f"  inline <svg> blocks: {inline_chars}")
print(f"  asset <img> tags   : {img_count}")
print(f"  xlink:href hotspots: {hit}")

INLINE_SET = sorted(INLINE_CARDS)
print(f"  inline-cards list  : {INLINE_SET}")
